[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:24:10"
timestamp_intended_ISO = "2025-03-10T00:24:04"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:24:28"
timestamp_intended_ISO = "2025-03-10T04:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = true
foam_present = false
oil_present = false
operator = "Henry Lee Clark"

