[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:24:10"
timestamp_intended_ISO = "2025-03-10T00:24:04"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:24:28"
timestamp_intended_ISO = "2025-03-10T04:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = true
foam_present = false
oil_present = false
operator = "Henry Lee Clark"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:55:02"
timestamp_intended_ISO = "2025-03-10T00:54:52"
safe_to_make_observation = true
flotable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Dalvin Foster"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:55:27"
timestamp_intended_ISO = "2025-04-10T09:00:52"
safe_to_make_observation = true
flotable_present = true
scum_present = true
foam_present = true
oil_present = true
operator = "Glady Nakayama"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T01:18:55"
timestamp_intended_ISO = "2025-03-10T01:18:53"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:17:51"
timestamp_intended_ISO = "2025-03-10T16:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Henry Lee Clark"
source = "web-post-Python-uvicorn"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:38:39"
timestamp_intended_ISO = "2025-03-10T15:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:38:43"
timestamp_intended_ISO = "2025-03-10T15:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:05:26"
timestamp_intended_ISO = "2025-03-10T15:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:05:30"
timestamp_intended_ISO = "2025-03-10T15:00:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:06:03"
timestamp_intended_ISO = "2025-03-10T13:06:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:06:57"
timestamp_intended_ISO = "2025-03-10T13:06:00"
safe_to_make_observation = true
flotable_present = true
scum_present = false
foam_present = false
oil_present = true
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

