[[hourly_data]]
timestamp = "2025-03-07T12:07:45"
clarifier_status = "spinning backwards"
observations = "coffee x3"

[[hourly_data]]
timestamp = "2025-03-07T12:08:41"
clarifier_status = "spinning forwards"
observations = "coffee x2"

[[hourly_data]]
timestamp = "2025-03-07T12:23:19"
clarifier_status = "stopped"
observations = "coffee x1"

[[hourly_data]]
timestamp = "2025-03-07T12:24:04"
clarifier_status = "stopped"

[[hourly_data]]
timestamp = "2025-03-07T12:24:27"

[[hourly_data]]
timestamp = "2025-03-07T12:25:24"
observations = "coffee x1"

