[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:24:49"
timestamp_intended_ISO = "2025-03-10T00:24:32"
influent_flow_rate_MGD = 99.0
after_wet_well_flow_rate_MGD = 98.0
effluent_flow_rate_MGD = 93.0
was_flow_rate_MGD = 1.4
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T00:25:16"
timestamp_intended_ISO = "2025-03-10T04:00:00"
influent_flow_rate_MGD = 87.0
after_wet_well_flow_rate_MGD = 86.0
effluent_flow_rate_MGD = 84.0
was_flow_rate_MGD = 1.5
operator = "Henry Lee Clark"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T01:19:18"
timestamp_intended_ISO = "2025-03-10T01:19:14"
influent_flow_rate_MGD = 0.0
after_wet_well_flow_rate_MGD = 0.0
effluent_flow_rate_MGD = 0.0
was_flow_rate_MGD = 0.0
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T01:20:25"
timestamp_intended_ISO = "2025-03-10T01:20:23"
influent_flow_rate_MGD = 0.0
after_wet_well_flow_rate_MGD = 0.0
effluent_flow_rate_MGD = 0.0
was_flow_rate_MGD = 0.0
operator = "Clayton Bennett"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:32:41"
timestamp_intended_ISO = "2025-03-10T12:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 50.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Clayton Bennett"
source = "web-post-Python-uvicorn"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:34:34"
timestamp_intended_ISO = "2025-03-10T13:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Henry Winkler"
source = "web-post-Python-uvicorn"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:36:43"
timestamp_intended_ISO = "2025-03-10T13:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:36:53"
timestamp_intended_ISO = "2025-03-10T13:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:38:36"
timestamp_intended_ISO = "2025-03-10T12:38:36"
influent_flow_rate_MGD = 67.0
after_wet_well_flow_rate_MGD = 66.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T12:38:41"
timestamp_intended_ISO = "2025-03-10T13:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:05:24"
timestamp_intended_ISO = "2025-03-10T13:05:24"
influent_flow_rate_MGD = 67.0
after_wet_well_flow_rate_MGD = 66.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:05:28"
timestamp_intended_ISO = "2025-03-10T13:00:00"
influent_flow_rate_MGD = 100.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 63.0
was_flow_rate_MGD = 1.5
operator = "Batch Eval"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:24:00"
timestamp_intended_ISO = "2025-03-10T14:00:00"
influent_flow_rate_MGD = 1.5
after_wet_well_flow_rate_MGD = 2.0
effluent_flow_rate_MGD = 1.8
was_flow_rate_MGD = 0.5
operator = "JohnDoe"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T13:24:00"
timestamp_intended_ISO = "2025-03-10T14:00:00"
influent_flow_rate_MGD = 1.5
after_wet_well_flow_rate_MGD = 2.0
effluent_flow_rate_MGD = 1.8
was_flow_rate_MGD = 0.5
operator = "JohnDoe"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T16:10:09"
timestamp_intended_ISO = "2025-03-10T16:09:00"
influent_flow_rate_MGD = 88.0
after_wet_well_flow_rate_MGD = 87.0
effluent_flow_rate_MGD = 86.0
was_flow_rate_MGD = 1.0
operator = "Mike Durham"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T16:11:09"
timestamp_intended_ISO = "2025-03-10T16:11:00"
influent_flow_rate_MGD = 1.0
after_wet_well_flow_rate_MGD = 5.0
effluent_flow_rate_MGD = 6.0
was_flow_rate_MGD = 8.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T16:23:58"
timestamp_intended_ISO = "2025-03-10T15:23:00"
influent_flow_rate_MGD = 88.0
after_wet_well_flow_rate_MGD = 87.0
effluent_flow_rate_MGD = 82.0
was_flow_rate_MGD = 1.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T16:24:33"
timestamp_intended_ISO = "2025-03-10T16:23:00"
influent_flow_rate_MGD = 88.0
after_wet_well_flow_rate_MGD = 86.0
effluent_flow_rate_MGD = 82.0
was_flow_rate_MGD = 1.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T16:24:59"
timestamp_intended_ISO = "2025-03-10T16:24:41"
after_wet_well_flow_rate_MGD = 98.0
effluent_flow_rate_MGD = 91.0
was_flow_rate_MGD = 3.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-10T20:40:14"
timestamp_intended_ISO = "2025-03-10T20:40:10"
influent_flow_rate_MGD = 0.0
after_wet_well_flow_rate_MGD = 0.0
effluent_flow_rate_MGD = 0.0
was_flow_rate_MGD = 0.0
operator = "Clayton Bennett"
source = "local-gui-Python-FreeSimpleGUI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T07:30:14"
timestamp_intended_ISO = "2025-03-11T07:29:57"
after_wet_well_flow_rate_MGD = 97.0
effluent_flow_rate_MGD = 67.0
was_flow_rate_MGD = 1.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T07:45:27"
timestamp_intended_ISO = "2025-03-11T07:45:14"
after_wet_well_flow_rate_MGD = 98.0
effluent_flow_rate_MGD = 91.0
was_flow_rate_MGD = 1.0
operator = "Clayton Bennett"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T10:10:37"
timestamp_intended_ISO = "2025-03-11T10:08:00"
influent_flow_rate_MGD = 0.1
after_wet_well_flow_rate_MGD = 0.1
effluent_flow_rate_MGD = 0.1
was_flow_rate_MGD = 0.1
operator = "Test"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T10:10:58"
timestamp_intended_ISO = "2025-03-11T10:10:00"
influent_flow_rate_MGD = 2.0
after_wet_well_flow_rate_MGD = 2.0
effluent_flow_rate_MGD = 2.0
was_flow_rate_MGD = 2.0
operator = "2"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T10:14:18"
timestamp_intended_ISO = "2025-03-11T10:10:00"
influent_flow_rate_MGD = 2.0
after_wet_well_flow_rate_MGD = 2.0
effluent_flow_rate_MGD = 2.0
was_flow_rate_MGD = 2.0
operator = "2"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T11:04:08"
timestamp_intended_ISO = "2025-03-11T11:03:00"
influent_flow_rate_MGD = 99.0
after_wet_well_flow_rate_MGD = 99.0
effluent_flow_rate_MGD = 99.0
was_flow_rate_MGD = 99.0
operator = "99"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T12:53:22"
timestamp_intended_ISO = "2025-03-11T12:53:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T12:53:53"
timestamp_intended_ISO = "2025-03-11T12:53:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T12:54:09"
timestamp_intended_ISO = "2025-03-11T12:53:00"
influent_flow_rate_MGD = 0.1
after_wet_well_flow_rate_MGD = 0.1
effluent_flow_rate_MGD = 0.1
was_flow_rate_MGD = 0.1
operator = "Kale Carmon"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T12:54:25"
timestamp_intended_ISO = "2025-03-11T12:53:00"
influent_flow_rate_MGD = 0.1
after_wet_well_flow_rate_MGD = 0.1
effluent_flow_rate_MGD = 0.1
was_flow_rate_MGD = 0.1
operator = "Kale Carmon"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T13:58:30"
timestamp_intended_ISO = "2025-03-11T13:58:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:09:15"
timestamp_intended_ISO = "2025-03-11T14:09:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:11:37"
timestamp_intended_ISO = "2025-03-11T14:09:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:23:29"
timestamp_intended_ISO = "2025-03-11T14:23:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:31:11"
timestamp_intended_ISO = "2025-03-11T14:31:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:31:54"
timestamp_intended_ISO = "2025-03-11T14:31:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:31:59"
timestamp_intended_ISO = "2025-03-11T14:31:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:34:06"
timestamp_intended_ISO = "2025-03-11T14:31:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:34:13"
timestamp_intended_ISO = "2025-03-11T14:34:00"
source = "web-post-Python-FastAPI"

[[hourly_data]]
timestamp_entry_ISO = "2025-03-11T14:34:28"
timestamp_intended_ISO = "2025-03-11T14:34:00"
source = "web-post-Python-FastAPI"

